# Generated by Django 3.1.6 on 2023-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_connection_post_profile_reaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('user', 'follower'), name='unique connection'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique reaction'),
        ),
    ]
