# Generated by Django 3.1.6 on 2023-07-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20230707_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
