# Generated by Django 3.1.6 on 2023-07-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20230713_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
