# Generated by Django 5.2.3 on 2025-11-06 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_reaction_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(help_text='Bookmarked post.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='feed.post'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_date'], name='feed_bookma_user_id_c8b609_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_date'], name='feed_commen_post_id_c636fd_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', '-created_date'], name='feed_follow_followe_b6a551_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', '-created_date'], name='feed_follow_followe_000c45_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_date'], name='feed_post_author__fc70c0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent', '-created_date'], name='feed_post_parent__021737_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-is_pinned', '-created_date'], name='feed_post_author__9bffa0_idx'),
        ),
    ]
