# Generated by Django 5.2.3 on 2025-11-07 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_bookmark_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('body', ''), ('body__isnull', True), _connector='OR'), fields=('author', 'parent'), name='unique_repost_per_user'),
        ),
    ]
